Algoritmo "Exercício idades"

Var
nome1, nome2 : caractere
idade1, idade2, idade_media: real
Inicio
      escreval("Digite o nome da primeira pessoa: ")
      leia(nome1)
      escreval("Digite a idade da primeira pessoa: ")
      leia(idade1)
      escreval("Digite o nome da segunda pessoa: ")
      leia(nome2)
      escreval("Digite a idade da segunda pessoa: ")
      leia(idade2)
      idade_media <- (idade1 + idade2) / 2
      escreval("A idade média de ", nome1, " e ", nome2, " é de", idade_media, " anos")

Fimalgoritmo